// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjlwgteomftjvaaayxjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqbHdndGVvbWZ0anZhYWF5eGpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNzY0MTgsImV4cCI6MjA1NTc1MjQxOH0.QLTymImYCIsRNax_hK_038QKQL7hMRcAre6TXCQIqjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);